export const LangValue = {
    'en': {
        LOGIN:'Login',
        WELCOME:'Welcome',
        EMAIL_ID:'Email Id',
        PASSWORD:'Password',
        REMEMBER_PASSWORD:'Remember Password',
        FORGOT_PASSWORD:'Forgot Password ?',
        DO_NOT_HAVE_ACCOUNT:'Do not have account?',
        REGISTER_HERE:'Register Here',
        INVALID_EMAIL:'Invalid E-mail Address',
        PASSWORD_BLANK:'Please enter your password',
        SUBMIT:'Submit',

        CHANGE_PASSWORD:'Change Password',
        OLD_PASSWORD:'Old Password',
        NEW_PASSWORD:'New Password',
        GENERATE_PASSWORD: 'Generate Password',
        OTP_SENT_TO_EMAIL: 'OTP sent to your Email',
        ORDER_STATUS : 'Order Status',
        DONE: 'Done',
        NOT_AVAILABLE:'Not Available',
        ORDER_TOTAL: 'Order Total',
        VIEW_PRODUCTS:'View Products',
        CITY:'City',
        CALL:'Call',
        OK:'OK',
        COMPANY_ADDRESS:'Company Address',
        ADD_TO_CART:'Add To Cart',
        SELECT_DELIVERY_TIME:'Select Delivery Time',
        PAY_NOW:'Pay Now',
        MORE_DETAIL:'More Detail',
        GAS_WATER_SERVICES:'Gas & Water Services',
        RENEW:'Renew',
        PROFILE_DETAILS:'Profile Details',
    },
    'ar': {
        LOGIN:'تسجيل الدخول',
        WELCOME:'مرحبا',
        EMAIL_ID:'البريد الإلكتروني',
        PASSWORD:'كلمة المرور',
        REMEMBER_PASSWORD:'تذكير كلمة المرور',
        FORGOT_PASSWORD:'نسيىت كلمة المرور؟',
        DO_NOT_HAVE_ACCOUNT:'ليس لديك حساب؟',
        REGISTER_HERE:'سجل هنا ',
        INVALID_EMAIL:'البريد الإلكتروني غير صحيح',
        PASSWORD_BLANK:'أدخل كلمة المرور',
        SUBMIT:'موافق',

        CHANGE_PASSWORD:'تغيير كلمة المرور ',
        OLD_PASSWORD:'كلمة المرور القديمة ',
        NEW_PASSWORD:'كلمة المرور الجديدة ',
        GENERATE_PASSWORD: 'انشأ كلمة المرور',
        OTP_SENT_TO_EMAIL: 'تم ارسال الرمز إلى بريدك الإلكتروني',
        ORDER_STATUS:'حالة الطلب ',
        DONE: 'تم ',
        NOT_AVAILABLE:'غير متاح',
        ORDER_TOTAL: 'مجموع الطلبات ',
        VIEW_PRODUCTS:'مشاهدة المنتجات',
        CITY:'المدينة',
        CALL:'اتصال ',
        OK:'نعم ',
        COMPANY_ADDRESS:'عنوان الشركة ',
        ADD_TO_CART:'اضافة إلى السلة ',
        SELECT_DELIVERY_TIME:'اختر وقت التوصيل ',
        PAY_NOW:'إدفع الآن ',
        MORE_DETAIL:'تفاصيل أكثر ',
        GAS_WATER_SERVICES:'خدمات الغاز و الماء',
        RENEW:'تجديد ',
        PROFILE_DETAILS:'تفاصيل الملف الشخصي',
    }
}